import { defineField, defineType } from 'sanity'

export const productType = defineType({
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'name' },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
    }),
    defineField({
      name: 'ingredients',
      title: 'Ingredients',
      type: 'text',
      description: 'List the ingredients used (e.g. Toor dal, onion, tomato)',
    }),
    defineField({
      name: 'allergens',
      title: 'Allergens',
      type: 'string',
      description: 'List any allergens (e.g. May contain dairy)',
    }),
    defineField({
      name: 'price',
      title: 'Price',
      type: 'number',
      validation: (rule) => rule.required().positive(),
    }),
    defineField({
      name: 'originalPrice',
      title: 'Original Price',
      type: 'number',
    }),
    defineField({
      name: 'servingSize',
      title: 'Serving Size',
      type: 'string',
      description: 'e.g. 750g, 500g, 2 pcs',
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'category' }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'video',
      title: 'Product Video',
      type: 'file',
      options: { accept: 'video/mp4,video/webm' },
      description: 'Upload an MP4 or WebM video for this product.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'thumbnail',
      title: 'Product Thumbnail (for PDF Catalog)',
      type: 'image',
      options: { hotspot: true },
      description: 'Upload a JPG/PNG photo of this dish. Used in the downloadable PDF catalog. Recommended: 800x533px (3:2 ratio).',
    }),
    defineField({
      name: 'isSpicy',
      title: 'Is Spicy?',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'vegetarian',
      title: 'Is Vegetarian?',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'signature',
      title: 'Is Signature?',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'isBestSeller',
      title: 'Is Best Seller?',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'includedRaita',
      title: '🥣 Includes Free Raita?',
      type: 'boolean',
      description: 'Turn ON to offer a free Raita add-on with this item (e.g. Biryani). Customer can opt-in when ordering.',
      initialValue: false,
    }),
    defineField({
      name: 'availabilityStatus',
      title: '📦 Availability Status',
      type: 'string',
      description: 'Controls the live badge shown to customers on your menu.',
      options: {
        list: [
          { title: '🟢 Available Today', value: 'available' },
          { title: '🟠 Limited Availability', value: 'limited' },
          { title: '🟣 Pre-Order Only', value: 'preorder' },
          { title: '🔴 Sold Out', value: 'soldout' },
        ],
        layout: 'radio',
      },
      initialValue: 'available',
    }),
    defineField({
      name: 'available',
      title: 'Is Available? (Legacy — use Availability Status above)',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'sortOrder',
      title: 'Sort Order',
      type: 'number',
      initialValue: 0,
    }),
  ],
})
